language: node_js

node_js:
  - 10

branches:
  except:
    - master
    - develop

env:
  global:
    - PATH=$PATH:./node_modules/.bin
    - secure: 1UqaOdvbIPbTGU4jrnL5lw0CSO5xYgMBIvssmFyWRDBqpYIP/q36mAZJNjt51JB8OV7h/ZEdeZSZc+ehz76QVW0l8TRMvNcJ4TafVlAoGs5F7iH5pW0KjHscJrvLM1eVIERC0AhD1NouYq94Zl73mC6mSUEi/tPVC2HlLkqq+rxSSeL+hSpxhagD/AuwowuZ3Y72wVJaOTqj0Ft/T9KmQ1h9b845k0qEfcFUK9TNiGvUpKF1tT/H+s7ill5K5FT3IcSgpIpfhzkD+OwWXDEthTLRgeNjOebRudbSW4PePMacegEn6Vno+Tm4qJtfsoJvM//fv7DPMIpLgjuLIvSQDA==
build:
  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    - npm install --no-audit --ignore-scripts
    - npm run lint
  on_success:
    - npx ci-semantic-release

resources:
    - name:             kendo-angular-messages-repo
      type:             gitRepo
      integration:      github-telerik
      versionTemplate:
        sourceName:       telerik/kendo-angular-messages
        branch:           develop
jobs:
  - name: kendo-angular-messages-publish_develop_as_latest
    type: runSh
    steps:
      - IN: kendo-angular-messages-repo
      - IN: kendo-angular-messages_ciRepo
        switch: off
      - TASK:
          name: kendo-angular-messages-publish_develop
          script:
            - ssh-add $KENDOANGULARMESSAGESREPO_KEYPATH
            - cd $KENDOANGULARMESSAGESREPO_STATE && git checkout master && git pull --rebase
            - npm install @telerik/semantic-prerelease@1 --no-save && npx release-master
